[[wolfSSL]]
arch = "aarch64"
git-tree-sha1 = "804dca3f132547e86e3b8a68dfc352cb1ddd08b8"
os = "macos"

    [[wolfSSL.download]]
    sha256 = "cfbf0db2621766a444d93b40dfe3ee8278875cf508291a1f71d633f4104838e1"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.aarch64-apple-darwin.tar.gz"
[[wolfSSL]]
arch = "aarch64"
git-tree-sha1 = "3bb32ce7f91beff5fede25421b013ac024d3e56d"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "a52b8ef0e8cfc8848eefab3ba5a14d575f21d444bab70b4eadc953f3957b85c5"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.aarch64-linux-gnu.tar.gz"
[[wolfSSL]]
arch = "aarch64"
git-tree-sha1 = "4f6f436bd89cc25b378b6d3bb8f428265ed2dbf6"
libc = "musl"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "5b09bc909fab71d08541f5bcc5e36e093cb9898907422a1cfe72a67bc0928ae4"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.aarch64-linux-musl.tar.gz"
[[wolfSSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a58d9ce423269330022f8630fd36273ae80c217"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "ee3d28523433613927bee5ae44b71a0859f1d878789d327c54066f116a32496c"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.armv6l-linux-gnueabihf.tar.gz"
[[wolfSSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d6c28fd6bd52ac2953959ed60b4d748833e2f32"
libc = "musl"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "29ed6745433373cb98517b93e82d48109781ef97b05c4bb9913d59886d3cd7d0"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.armv6l-linux-musleabihf.tar.gz"
[[wolfSSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5dc7a24017e7c7f64d2c9557a38d79b524321be5"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "58fb7aab3e3cf6710229e2532781898eba1b8b09e5c0a02fee39dc53e7a9ae33"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.armv7l-linux-gnueabihf.tar.gz"
[[wolfSSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "acfe22ba9e242ff736099b098603e118943b7f9c"
libc = "musl"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "674acf075742d66e055bdb9227a1b1d6a79730f6a4c794d224f451b0d68fe4af"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.armv7l-linux-musleabihf.tar.gz"
[[wolfSSL]]
arch = "i686"
git-tree-sha1 = "3259afafb72c5077a8b14cbbde1233986eae15b6"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "a5c4d22ae1bf1fa188c1a61bff4fb9c11816bfec77984c1daacdac1d44a64f21"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.i686-linux-gnu.tar.gz"
[[wolfSSL]]
arch = "i686"
git-tree-sha1 = "5f54b3a87e3b9f421b359d63969615cc0755077c"
libc = "musl"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "44df34151b34c26edf5aa1c895cdbe81aad4be960e07dc403db74bdbeefb92fd"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.i686-linux-musl.tar.gz"
[[wolfSSL]]
arch = "i686"
git-tree-sha1 = "72aafd2f2f04daacd2e2bb4e7613f8d40d3f4580"
os = "windows"

    [[wolfSSL.download]]
    sha256 = "e0da4166c4a517f48c14edcd30022120ac1d9ccf5cd86712ee0f1f58a85a7f6f"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.i686-w64-mingw32.tar.gz"
[[wolfSSL]]
arch = "powerpc64le"
git-tree-sha1 = "0530abb6e93e995ca713d971e946774c9440295e"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "dd36b923aab81ff2ea421dfdabe6e697706e5a28133a846a0c9095a6c8fe5fdb"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.powerpc64le-linux-gnu.tar.gz"
[[wolfSSL]]
arch = "x86_64"
git-tree-sha1 = "7e306c92eb502b9390abc912ced56a044d44f9a3"
os = "macos"

    [[wolfSSL.download]]
    sha256 = "46c87583324904483505b9ee40d77cef5eaed93967235dcf3c0019f87126dedb"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.x86_64-apple-darwin.tar.gz"
[[wolfSSL]]
arch = "x86_64"
git-tree-sha1 = "41987dd2dab3987977b60b99dfecded9871ecfeb"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "ca389228856608df4591e2ccb49fe642b3133d191c14437cd443dee6c3961212"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.x86_64-linux-gnu.tar.gz"
[[wolfSSL]]
arch = "x86_64"
git-tree-sha1 = "27f522b7cdcf17b1eaf91ca166e372df582bc308"
libc = "musl"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "558e6e7c93e4ec0f9b126e1d22286405994c157644fa814ab5e61d61173f754c"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.x86_64-linux-musl.tar.gz"
[[wolfSSL]]
arch = "x86_64"
git-tree-sha1 = "db9654a9e22cce4a238a27b7d64156eb00fc6046"
os = "freebsd"

    [[wolfSSL.download]]
    sha256 = "8ccf3dd75d27ed6ce3590fdb7a16d3a612f22ff03c741baaa9b98214627329cc"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.x86_64-unknown-freebsd.tar.gz"
[[wolfSSL]]
arch = "x86_64"
git-tree-sha1 = "9b6503a6af55066bda4ccb412df8be6721fe704a"
os = "windows"

    [[wolfSSL.download]]
    sha256 = "9bc5eae2d5d1a9c0dc3a6330f706aa5c495650c4a85cc4e34d8329b1d5853da3"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v4.8.1+0/wolfSSL.v4.8.1.x86_64-w64-mingw32.tar.gz"
