[[wolfSSL]]
arch = "aarch64"
git-tree-sha1 = "75c567e96d339e501b8171219ec16eb982e49237"
os = "macos"

    [[wolfSSL.download]]
    sha256 = "304466dccef24e14cf03748cac31289cbb80f9a1e2a29b40192bd0177cb1cdcf"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.aarch64-apple-darwin.tar.gz"
[[wolfSSL]]
arch = "aarch64"
git-tree-sha1 = "5148453d66716d786d3263c7789390971ee4a324"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "d35499b602e8ee09d43cb97e3fd2e4cca6e9ae6c2d7093dd34a7b5f4363c3046"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.aarch64-linux-gnu.tar.gz"
[[wolfSSL]]
arch = "aarch64"
git-tree-sha1 = "461469cbf4ce2c55ff56950d973d3fde94cc89e2"
libc = "musl"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "60192084ccaf7ef501b97c6fb48b8b75d50bb96d0afa1ded80aacf0240333942"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.aarch64-linux-musl.tar.gz"
[[wolfSSL]]
arch = "aarch64"
git-tree-sha1 = "1450a0d6d68d4c53a369c7732ed3f0d65bb93827"
os = "freebsd"

    [[wolfSSL.download]]
    sha256 = "cdf38c0c85218ea366c3aa974e76d536a79a7b6a9980f2d5400b8764905ab905"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.aarch64-unknown-freebsd.tar.gz"
[[wolfSSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "53045463b575681131a262dd327f7d44873414fe"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "83d3f73afd3d0be971fe709c2934008cb33351976b2476596a04078051c44ec9"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.armv6l-linux-gnueabihf.tar.gz"
[[wolfSSL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4df046b9fe0bc06c4b0bcde74b7235b34b5d7ffb"
libc = "musl"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "7101cd520830ab67346ef44cedc41464e00a731b76e3c5bf12d515c741f957e4"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.armv6l-linux-musleabihf.tar.gz"
[[wolfSSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7470b94265abd520a5c2f2a913a7dc200f511d36"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "3ddf465fc88eb24d9f95be75892588fb50f038befad2596ab4c90dcf80a3557f"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.armv7l-linux-gnueabihf.tar.gz"
[[wolfSSL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6bbc66dde3f56483693c4e3292163732bdd2c953"
libc = "musl"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "60644d8b796ecfb7e92e1c3206fdfa72d24fc1502896873c1891ed2afde2932b"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.armv7l-linux-musleabihf.tar.gz"
[[wolfSSL]]
arch = "i686"
git-tree-sha1 = "a8e036710757184f38d46eeb305c246e502af37f"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "f7318604b08e39fef9eeb8fcbcbeac897762c850e22a6a1d0bcb4d3ecda653ae"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.i686-linux-gnu.tar.gz"
[[wolfSSL]]
arch = "i686"
git-tree-sha1 = "575f792ad170827f2a98d3bf33ccdf325c90fc81"
libc = "musl"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "3d9cb6fdc1ade61463296c56ffa799f348c33c331318397ca4f6eb485da862db"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.i686-linux-musl.tar.gz"
[[wolfSSL]]
arch = "i686"
git-tree-sha1 = "ce86d8f2c189abb01d2a3696b30ac10f187b9822"
os = "windows"

    [[wolfSSL.download]]
    sha256 = "620dbec2e593bbfc64195b2caa43d2f53ff22d05d9ebb14dfddf59c15d2dee82"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.i686-w64-mingw32.tar.gz"
[[wolfSSL]]
arch = "powerpc64le"
git-tree-sha1 = "af73f8dd2f3d63033c23fbb2f1503d06c9364478"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "6b10e2d21895a7315339e9810628472b29df34ffc53d3bd56a3770348f05df45"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.powerpc64le-linux-gnu.tar.gz"
[[wolfSSL]]
arch = "x86_64"
git-tree-sha1 = "a6bac6e24f3adcac02b677829d95ed4e905c66a2"
os = "macos"

    [[wolfSSL.download]]
    sha256 = "0d4e3793c9f0edf3ea45ec5791e03bae457c8f3a03d34fd7194a9209d4a48efb"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.x86_64-apple-darwin.tar.gz"
[[wolfSSL]]
arch = "x86_64"
git-tree-sha1 = "eef026dd17fa1c5eb8d84499ba0bf9d6c4aff0ad"
libc = "glibc"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "9830db198750e671ea1d690fc4eff47de3d6603cbdc82224520b92d543b0e2e8"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.x86_64-linux-gnu.tar.gz"
[[wolfSSL]]
arch = "x86_64"
git-tree-sha1 = "da0270a0d102b3d8f14da8416e39c2a4f1698d34"
libc = "musl"
os = "linux"

    [[wolfSSL.download]]
    sha256 = "e3285af483902a2d620cb4da45ef513b96d5307d94a3d8a50d60d533d49c94e9"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.x86_64-linux-musl.tar.gz"
[[wolfSSL]]
arch = "x86_64"
git-tree-sha1 = "edf0116516cfce62b011662a311ce946700d36aa"
os = "freebsd"

    [[wolfSSL.download]]
    sha256 = "b1c8d57701ec00aa4cbceabe36ba9368c36eb8867f983235c49b5a58c661c3a8"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.x86_64-unknown-freebsd.tar.gz"
[[wolfSSL]]
arch = "x86_64"
git-tree-sha1 = "12f5d8eceb1ecefaec6c6f316e4d1c12389bb419"
os = "windows"

    [[wolfSSL.download]]
    sha256 = "d0bb9c73debcfe2afa65d954d726a3deb9edfd3bca8545324888e49aa651f96f"
    url = "https://github.com/JuliaBinaryWrappers/wolfSSL_jll.jl/releases/download/wolfSSL-v5.7.2+0/wolfSSL.v5.7.2.x86_64-w64-mingw32.tar.gz"
